# Generated by Django 5.0.4 on 2024-04-28 15:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('NG', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='composition',
        ),
        migrations.RemoveField(
            model_name='product',
            name='description',
        ),
        migrations.RemoveField(
            model_name='product',
            name='prodapp',
        ),
        migrations.RemoveField(
            model_name='product',
            name='product_image',
        ),
    ]
